
   
apiVersion: v1
kind: Service
metadata:
  name: mf-execute-action
  labels:
    name: mf-execute-action
    version: v1
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mf-execute-action
  type: ClusterIP
