apiVersion: apps/v1
kind: Deployment
metadata:
  name: mf-execute-action
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mf-qrs
  template:
    metadata:
      labels:
        app: mf-execute-action
        version: v1
    spec:
      containers:
        - name: mf-execute-action
          image: LOCATION-gcr.io/vas-qr/IMAGE_NAME:TAG
          ports:
            - containerPort: 80
